# Association matrices -----------------------------------------------------------------------------

#' @name association
#'
#' @title Association Matrices for Fitting the Multivariate Box-Cox Symmetric Distributions Generated by
#'     a Normal Scale Mixture Copula
#'
#' @description  Class of association matrices available in the \code{bcnsm} package.
#'
#' @param d dimension of the association matrix.
#'
#' @return An object of class \code{"association"}, mainly used in the \code{bcnsm_fit} function. It
#'      returns a list with the components
#'         \describe{
#'           \item{npar}{number of parameters relative to the association structure.}
#'           \item{start}{a function \code{function(x)} which returns the initial values for the
#'               parameters related to the association matrix based on a matrix data \code{x}.}
#'           \item{Gamma}{a function \code{function(gamma)} that returns the association matrix as a
#'               function of the parameters \code{gamma}.}
#'           \item{lower, upper}{lower and upper bounds of the possible values assumed by the
#'               parameters relative to the association matrix.}
#'           \item{name}{character, with the name of the association structure.}
#'         }
#'
#' @details The normal scale mixture copula entirely describes the dependence structure of the
#'     BCNSM distributions. Because copulas are invariant under strictly increasing transformations,
#'     copula-based measures of association of the scale mixtures of normal distributions are the
#'     same for the BCNSM distributions. This statement is valid for measures of concordance, such
#'     as Kendall's tau or the tail dependence coefficients.
#'
#'     Let \code{gamma_ij} be the element of the ith row and jth column of the association matrix,
#'     say a d-dimensional \code{Gamma}, where \code{gamma_ii = 1}, for \code{i, j = 1, ..., d}. If
#'     \code{Y = (Y1, ..., Yd)}' is a d-dimensional random vector with a BCNSM distribution and with
#'     association matrix \code{Gamma}. Thus, Kendall's tau of \code{Yi} and \code{Yj} is given by
#'
#'     \code{tau(Yi, Yj) = 2 * asin(gamma_ij) / pi},
#'
#'     for \code{i, j = 1, ..., d} and it is invariant under the copula. Since Kendall’s tau is a
#'     rank correlation coefficient, it measures any monotonous association between two random variables.
#'     Thus, we have an increasing monotonous association between \code{Yi} and \code{Yj} when \code{gamma_ij}
#'     is close to 1, and a decreasing monotonous association when \code{gamma_ij} is close to -1.
#'     Furthermore, \code{gamma_ij = 0} indicates no monotonous association. These facts show that
#'     the association matrix \code{Gamma} plays an essential role in specifying the dependence
#'     structure of \code{Y}. It can be parameterized in terms of a real-valued vector \code{gamma}
#'     in an interpretative way depending on the type of association that is of interest to describe.
#'     Currently, the \code{bcnsm} package provides the non-associative, unstructured, and
#'     uniform (or exchangeable) association structures.
#'
#' @references Medeiros, R. M. R. de, and Ferrari, S. L. P. (2024). Multivariate Box-Cox symmetric
#'      distributions generated by a normal scale mixture copula.
#'
#' @author Rodrigo M. R. de Medeiros <\email{rodrigo.matheus@live.com}>
#'
#' @examples
#' ## Non-associative
#' nonassociative()
#' nonassociative(4)$Gamma()
#'
#' ## Unstructured
#' unstructured(4)
#' unstructured(4)$Gamma(c(0.2, 0.3, 0.4, 0.5, 0.6, 0.2))
#'
#' ## Uniform
#' uniform()
#' uniform(4)$Gamma(0.6)
#'
NULL

## Nonassociative ----------------------------------------------------------------------------------
#' @rdname association
#' @export
nonassociative <- function(d) {
  ans <- list()

  ans$npar <- 0L

  ans$start <- function(x) NULL

  ans$Gamma <- function(gamma = NULL) diag(d)

  ans$lower <- NULL
  ans$upper <- NULL

  ans$name <- "non-associative"

  class(ans) <- "association"
  ans
}


## Unstructured ------------------------------------------------------------------------------------
#' @rdname association
#' @export
unstructured <- function(d) {
  ans <- list()

  ans$npar <- d * (d - 1) / 2

  ans$start <- function(x){

    G <- sin(0.5 * pi * stats::cor(x, method = "kendall"))
    G[lower.tri(G, diag = TRUE)] <- NA

    gamma <- as.numeric(stats::na.exclude(c(t(G))))

  }

  ans$Gamma <- function(gamma) {
    class(gamma) <- "dist"
    attr(gamma, "Size") <- d
    gamma <- as.matrix(gamma)
    diag(gamma) <- 1
    gamma
  }

  EPS <- sqrt(.Machine$double.eps)
  ans$lower <- rep(-1 + EPS, d * (d - 1) / 2)
  ans$upper <- rep(1 - EPS, d * (d - 1) / 2)

  ans$name <- "unstructured"

  class(ans) <- "association"
  ans
}

### Uniform (exchangeable) -------------------------------------------------------------------------
#' @rdname association
#' @export
uniform <- function(d) {
  ans <- list()

  ans$npar <- 1

  ans$start <- function(x) stats::median(sin(0.5 * pi * stats::cor(x, method = "kendall"))[lower.tri(diag(d))])

  ans$Gamma <- function(gamma) {
    out <- matrix(gamma, d, d)
    diag(out) <- 1
    out
  }

  EPS <- sqrt(.Machine$double.eps)
  ans$lower <- -1 + EPS
  ans$upper <- 1 - EPS

  ans$name <- "uniform"

  class(ans) <- "association"
  ans
}

#' @name association_methods
#' @title Methods for 'association' objects
#' @param x an object of class \code{association}.
#' @param ... further arguments passed to or from other methods.
#'
#' @author Rodrigo M. R. de Medeiros <\email{rodrigo.matheus@live.com}>
#'
NULL

# Print method
# Class definition
#' @rdname association_methods
#' @export
print.association <- function(x, ...) {

  name <- x$name

  cat("\n------------------------------------\n")
  cat(sub("(.)", "\\U\\1", x$name, perl = TRUE), "association matrix")
  cat("\n------------------------------------\n")


  cat("Number of parameters:", x$npar, "\n")
}





